CREATE OR REPLACE VIEW TRAINING_DB.INTERMEDIATE.INT_SALES AS

SELECT
    l.ORDER_ID,
    l.LINE_NUMBER,

    o.CUSTOMER_ID,
    l.PART_ID,
    l.SUPPLIER_ID,

    o.ORDER_DATE,
    l.SHIP_DATE,
    l.COMMIT_DATE,
    l.RECEIPT_DATE,

    o.ORDER_STATUS,
    o.ORDER_PRIORITY,

    l.QUANTITY,
    l.EXTENDED_PRICE,
    l.DISCOUNT,
    l.TAX,

    l.EXTENDED_PRICE
        AS GROSS_SALES_AMOUNT,

    l.EXTENDED_PRICE * (1 - l.DISCOUNT)
        AS NET_SALES_AMOUNT,

    l.EXTENDED_PRICE
        * (1 - l.DISCOUNT)
        * (1 + l.TAX)
        AS SALES_AMOUNT_WITH_TAX,

    DATEDIFF(
        DAY,
        o.ORDER_DATE,
        l.SHIP_DATE
    ) AS DAYS_TO_SHIP,

    DATEDIFF(
        DAY,
        l.SHIP_DATE,
        l.RECEIPT_DATE
    ) AS SHIPPING_DURATION_DAYS,

    l.RETURN_FLAG,
    l.LINE_STATUS,
    l.SHIP_MODE

FROM TRAINING_DB.STAGING.STG_LINEITEM l

INNER JOIN TRAINING_DB.STAGING.STG_ORDERS o
    ON l.ORDER_ID = o.ORDER_ID;