CREATE OR REPLACE VIEW TRAINING_DB.INTERMEDIATE.INT_PART_SUPPLIER AS

SELECT
    ps.PART_ID,
    p.PART_NAME,
    p.MANUFACTURER,
    p.BRAND,
    p.PART_TYPE,
    p.PART_SIZE,

    ps.SUPPLIER_ID,
    s.SUPPLIER_NAME,

    ps.AVAILABLE_QUANTITY,
    ps.SUPPLY_COST,

    p.RETAIL_PRICE,

    p.RETAIL_PRICE - ps.SUPPLY_COST
        AS THEORETICAL_MARGIN_AMOUNT

FROM TRAINING_DB.STAGING.STG_PARTSUPP ps

INNER JOIN TRAINING_DB.STAGING.STG_PART p
    ON ps.PART_ID = p.PART_ID

INNER JOIN TRAINING_DB.STAGING.STG_SUPPLIER s
    ON ps.SUPPLIER_ID = s.SUPPLIER_ID;