USE SCHEMA TRAINING_DB.INTERMEDIATE;

CREATE OR REPLACE TABLE TRAINING_DB.INTERMEDIATE.TMP_CUSTOMER_CHANGES AS
SELECT
    src.*,
    CASE
        WHEN tgt.CUSTOMER_ID IS NULL THEN 'INSERT'
        WHEN
            tgt.CUSTOMER_NAME IS DISTINCT FROM src.CUSTOMER_NAME
            OR tgt.PHONE IS DISTINCT FROM src.PHONE
            OR tgt.ACCOUNT_BALANCE IS DISTINCT FROM src.ACCOUNT_BALANCE
            OR tgt.ADDRESS IS DISTINCT FROM src.ADDRESS
            OR tgt.MARKET_SEGMENT IS DISTINCT FROM src.MARKET_SEGMENT
            OR tgt.NATION_ID IS DISTINCT FROM src.NATION_ID
            OR tgt.NATION_NAME IS DISTINCT FROM src.NATION_NAME
            OR tgt.REGION_ID IS DISTINCT FROM src.REGION_ID
            OR tgt.REGION_NAME IS DISTINCT FROM src.REGION_NAME
        THEN 'UPDATE'
        ELSE 'NO_CHANGE'
    END AS CHANGE_TYPE
FROM TRAINING_DB.INTERMEDIATE.INT_CUSTOMER_GEO src
LEFT JOIN TRAINING_DB.DWH.DIM_CUSTOMER tgt
    ON src.CUSTOMER_ID = tgt.CUSTOMER_ID
   AND tgt.IS_ACTIVE = TRUE;
