SET LOAD_ID = TRAINING_DB.STAGING.SEQ_STG_LOAG_KEY.NEXTVAL;

CREATE OR REPLACE TABLE TRAINING_DB.STAGING.STG_NATION AS
SELECT
    TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS SOURCE_UPDATE_TS,

    N_NATIONKEY AS NATION_ID,
    N_NAME      AS NATION_NAME,
    N_REGIONKEY AS REGION_ID,
    N_COMMENT   AS COMMENT,

    $LOAD_ID       AS LOAD_ID,
    CURRENT_TIMESTAMP()                            AS STG_LOAD_TS

FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;