SET LOAD_ID = TRAINING_DB.STAGING.SEQ_STG_LOAG_KEY.NEXTVAL;

CREATE OR REPLACE TABLE TRAINING_DB.STAGING.STG_LINEITEM AS
SELECT
    TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS SOURCE_UPDATE_TS,

    L_ORDERKEY      AS ORDER_ID,
    L_PARTKEY       AS PART_ID,
    L_SUPPKEY       AS SUPPLIER_ID,
    L_LINENUMBER    AS LINE_NUMBER,
    L_QUANTITY      AS QUANTITY,
    L_EXTENDEDPRICE AS EXTENDED_PRICE,
    L_DISCOUNT      AS DISCOUNT,
    L_TAX           AS TAX,
    L_RETURNFLAG    AS RETURN_FLAG,
    L_LINESTATUS    AS LINE_STATUS,
    L_SHIPDATE      AS SHIP_DATE,
    L_COMMITDATE    AS COMMIT_DATE,
    L_RECEIPTDATE   AS RECEIPT_DATE,
    L_SHIPINSTRUCT  AS SHIP_INSTRUCTION,
    L_SHIPMODE      AS SHIP_MODE,
    L_COMMENT       AS COMMENT,

    $LOAD_ID       AS LOAD_ID,
    CURRENT_TIMESTAMP()                            AS STG_LOAD_TS

FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;