truncate table TRAINING_DB.STAGING.STG_CUSTOMER;

SET LOAD_ID = TRAINING_DB.STAGING.SEQ_STG_LOAD_KEY.NEXTVAL;

insert into TRAINING_DB.STAGING.STG_CUSTOMER
(
	SOURCE_UPDATE_TS,
	CUSTOMER_ID ,
	CUSTOMER_NAME,
	ADDRESS,
	NATION_ID,
	PHONE,
	ACCOUNT_BALANCE,
	MARKET_SEGMENT,
	COMMENT,
    LOAD_ID,
    STG_LOAD_TS
)
values (
TO_TIMESTAMP_NTZ('2026-09-12'),
1,
'LEONARD',
'Ui1b,3Q71CiLTJn4MbVp,,YCZARIaNTelfst',
4,
'14-526-204-4500',
8848.47,
'MACHINERY',
'frays wake blithely enticingly ironic asymptote',
$LOAD_ID,
CURRENT_TIMESTAMP()    
)