CREATE OR REPLACE VIEW TRAINING_DB.INTERMEDIATE.INT_SUPPLIER_GEO AS

SELECT
    s.SUPPLIER_ID,
    s.SUPPLIER_NAME,
    s.ADDRESS,
    s.PHONE,
    s.ACCOUNT_BALANCE,
    s.NATION_ID,

    n.NATION_NAME,
    n.REGION_ID,
    r.REGION_NAME

FROM TRAINING_DB.STAGING.STG_SUPPLIER s

LEFT JOIN TRAINING_DB.STAGING.STG_NATION n
    ON s.NATION_ID = n.NATION_ID

LEFT JOIN TRAINING_DB.STAGING.STG_REGION r
    ON n.REGION_ID = r.REGION_ID;