SET LOAD_ID = TRAINING_DB.STAGING.SEQ_STG_LOAG_KEY.NEXTVAL;

CREATE OR REPLACE TABLE TRAINING_DB.STAGING.STG_SUPPLIER AS
SELECT
    TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS SOURCE_UPDATE_TS,
    
    S_SUPPKEY   AS SUPPLIER_ID,
    S_NAME      AS SUPPLIER_NAME,
    S_ADDRESS   AS ADDRESS,
    S_NATIONKEY AS NATION_ID,
    S_PHONE     AS PHONE,
    S_ACCTBAL   AS ACCOUNT_BALANCE,
    S_COMMENT   AS COMMENT,

    $LOAD_ID       AS LOAD_ID,
    CURRENT_TIMESTAMP()                            AS STG_LOAD_TS

FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER;