SET LOAD_ID = TRAINING_DB.STAGING.SEQ_STG_LOAG_KEY.NEXTVAL;

CREATE OR REPLACE TABLE TRAINING_DB.STAGING.STG_REGION AS
SELECT
    TO_TIMESTAMP_NTZ('2026-01-01 00:00:00')         AS SOURCE_UPDATE_TS,
    
    R_REGIONKEY AS REGION_ID,
    R_NAME      AS REGION_NAME,
    R_COMMENT   AS COMMENT,

    $LOAD_ID       AS LOAD_ID,
    CURRENT_TIMESTAMP()                            AS STG_LOAD_TS

FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION;