SET LOAD_ID = TRAINING_DB.STAGING.SEQ_STG_LOAD_KEY.NEXTVAL;

CREATE OR REPLACE TABLE TRAINING_DB.STAGING.STG_CUSTOMER AS
SELECT
    TO_TIMESTAMP_NTZ('2026-01-01 00:00:00')        AS SOURCE_UPDATE_TS,

    C_CUSTKEY      AS CUSTOMER_ID,
    C_NAME         AS CUSTOMER_NAME,
    C_ADDRESS      AS ADDRESS,
    C_NATIONKEY    AS NATION_ID,
    C_PHONE        AS PHONE,
    C_ACCTBAL      AS ACCOUNT_BALANCE,
    C_MKTSEGMENT   AS MARKET_SEGMENT,
    C_COMMENT      AS COMMENT,
    
    $LOAD_ID       AS LOAD_ID,
    CURRENT_TIMESTAMP()                            AS STG_LOAD_TS

FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

