USE SCHEMA TRAINING_DB.INTERMEDIATE;

BEGIN TRANSACTION;

UPDATE TRAINING_DB.DWH.DIM_CUSTOMER tgt
SET
    VALID_TO = c.SOURCE_UPDATE_TS - INTERVAL '1 DAY',
    IS_ACTIVE = FALSE
FROM TMP_CUSTOMER_CHANGES c
WHERE c.CHANGE_TYPE = 'UPDATE'
  AND tgt.CUSTOMER_ID = c.CUSTOMER_ID
  AND tgt.IS_ACTIVE = TRUE;

INSERT INTO TRAINING_DB.DWH.DIM_CUSTOMER (
    SURROGATE_KEY,
    BUSINESS_DATE,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    ADDRESS,
    PHONE,
    ACCOUNT_BALANCE,
    MARKET_SEGMENT,
    NATION_ID,
    NATION_NAME,
    REGION_ID,
    REGION_NAME,
    LOAD_ID,
    VALID_FROM,
    VALID_TO,
    IS_ACTIVE,
    DWH_LOAD_TS
)
SELECT
    TRAINING_DB.DWH.SEQ_CUSTOMER_KEY.NEXTVAL,
    SOURCE_UPDATE_TS,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    ADDRESS,
    PHONE,
    ACCOUNT_BALANCE,
    MARKET_SEGMENT,
    NATION_ID,
    NATION_NAME,
    REGION_ID,
    REGION_NAME,
    LOAD_ID,
    SOURCE_UPDATE_TS,
    TO_DATE('31/12/2099', 'DD/MM/YYYY') VALID_TO,
    TRUE,
    CURRENT_TIMESTAMP()
FROM TRAINING_DB.INTERMEDIATE.TMP_CUSTOMER_CHANGES
WHERE CHANGE_TYPE IN ('INSERT', 'UPDATE');

COMMIT;
