CREATE OR REPLACE VIEW TRAINING_DB.INTERMEDIATE.INT_CUSTOMER_GEO AS

SELECT
    c.SOURCE_UPDATE_TS,

    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.ADDRESS,
    c.PHONE,
    c.ACCOUNT_BALANCE,
    c.MARKET_SEGMENT,
    c.NATION_ID,
    n.NATION_NAME,
    n.REGION_ID,
    r.REGION_NAME,

    c.LOAD_ID

FROM TRAINING_DB.STAGING.STG_CUSTOMER c

LEFT JOIN TRAINING_DB.STAGING.STG_NATION n
    ON c.NATION_ID = n.NATION_ID

LEFT JOIN TRAINING_DB.STAGING.STG_REGION r
    ON n.REGION_ID = r.REGION_ID;