CREATE DATABASE IF NOT EXISTS TRAINING_DB;

CREATE SCHEMA IF NOT EXISTS TRAINING_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS TRAINING_DB.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS TRAINING_DB.DWH;
CREATE SCHEMA IF NOT EXISTS TRAINING_DB.MART;

