USE SCHEMA TRAINING_DB.DWH;

CREATE SEQUENCE IF NOT EXISTS SEQ_CUSTOMER_KEY
    START = 1
    INCREMENT = 1;

CREATE SEQUENCE IF NOT EXISTS SEQ_PRODUCT_KEY
    START = 1
    INCREMENT = 1;

CREATE SEQUENCE IF NOT EXISTS SEQ_SUPPLIER_KEY
    START = 1
    INCREMENT = 1;

USE SCHEMA TRAINING_DB.STAGING;

CREATE SEQUENCE IF NOT EXISTS SEQ_STG_LOAD_KEY
    START = 1
    INCREMENT = 1;