CREATE ROLE IF NOT EXISTS TRAINING_ROLE;

GRANT USAGE
ON WAREHOUSE TRAINING_WH
TO ROLE TRAINING_ROLE;

GRANT USAGE
ON DATABASE TRAINING_DB
TO ROLE TRAINING_ROLE;

GRANT USAGE
ON ALL SCHEMAS IN DATABASE TRAINING_DB
TO ROLE TRAINING_ROLE;