CREATE OR REPLACE TABLE TRAINING_DB.MART.DIM_DATE AS

WITH DATE_RANGE AS (
    SELECT
        LEAST(
            MIN(ORDER_DATE),
            MIN(SHIP_DATE),
            MIN(COMMIT_DATE),
            MIN(RECEIPT_DATE)
        ) AS MIN_DATE,

        GREATEST(
            MAX(ORDER_DATE),
            MAX(SHIP_DATE),
            MAX(COMMIT_DATE),
            MAX(RECEIPT_DATE)
        ) AS MAX_DATE

    FROM TRAINING_DB.INTERMEDIATE.INT_SALES
),

DATES AS (
    SELECT
        DATEADD(
            DAY,
            SEQ4(),
            MIN_DATE
        ) AS DATE_DAY
    FROM DATE_RANGE,
         TABLE(GENERATOR(ROWCOUNT => 10000))
)

SELECT
    TO_NUMBER(TO_CHAR(DATE_DAY, 'YYYYMMDD')) AS DATE_KEY,
    DATE_DAY,

    YEAR(DATE_DAY) AS YEAR,
    QUARTER(DATE_DAY) AS QUARTER,
    MONTH(DATE_DAY) AS MONTH_NUMBER,
    MONTHNAME(DATE_DAY) AS MONTH_NAME,

    WEEKOFYEAR(DATE_DAY) AS WEEK_NUMBER,

    DAY(DATE_DAY) AS DAY_OF_MONTH,
    DAYOFWEEK(DATE_DAY) AS DAY_OF_WEEK_NUMBER,
    DAYNAME(DATE_DAY) AS DAY_NAME,

    CASE
        WHEN DAYOFWEEKISO(DATE_DAY) IN (6, 7)
        THEN TRUE
        ELSE FALSE
    END AS IS_WEEKEND,

    CURRENT_TIMESTAMP() AS MART_LOAD_TS

FROM DATES

WHERE DATE_DAY <= (
    SELECT MAX_DATE
    FROM DATE_RANGE
);