CREATE OR REPLACE TABLE TRAINING_DB.MART.DIM_PRODUCT AS
SELECT
    PART_ID        AS PRODUCT_ID,
    PART_NAME      AS PRODUCT_NAME,
    MANUFACTURER,
    BRAND,
    PART_TYPE      AS PRODUCT_TYPE,
    PART_SIZE      AS PRODUCT_SIZE,
    CONTAINER,
    RETAIL_PRICE,

    CURRENT_TIMESTAMP() AS MART_LOAD_TS

FROM TRAINING_DB.STAGING.STG_PART;