CREATE OR REPLACE TABLE TRAINING_DB.MART.DIM_SUPPLIER AS
SELECT
    SUPPLIER_ID,
    SUPPLIER_NAME,
    ADDRESS,
    PHONE,
    ACCOUNT_BALANCE,
    NATION_ID,
    NATION_NAME,
    REGION_ID,
    REGION_NAME,

    CURRENT_TIMESTAMP() AS MART_LOAD_TS

FROM TRAINING_DB.INTERMEDIATE.INT_SUPPLIER_GEO;