CREATE OR REPLACE TABLE TRAINING_DB.DWH.DIM_CUSTOMER AS
SELECT
    TRAINING_DB.DWH.SEQ_CUSTOMER_KEY.NEXTVAL AS SURROGATE_KEY,
    
    SOURCE_UPDATE_TS as BUSINESS_DATE,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    ADDRESS,
    PHONE,
    ACCOUNT_BALANCE,
    MARKET_SEGMENT,
    NATION_ID,
    NATION_NAME,
    REGION_ID,
    REGION_NAME,
    LOAD_ID,
    SOURCE_UPDATE_TS as VALID_FROM,
    TO_DATE('31/12/2099', 'DD/MM/YYYY') VALID_TO,
    TRUE as IS_ACTIVE,
    CURRENT_TIMESTAMP() AS DWH_LOAD_TS

FROM TRAINING_DB.INTERMEDIATE.INT_CUSTOMER_GEO;