CREATE OR REPLACE TABLE TRAINING_DB.MART.FACT_SALES AS
SELECT
    s.ORDER_ID,
    s.LINE_NUMBER,

    s.CUSTOMER_ID,
    s.PART_ID AS PRODUCT_ID,
    s.SUPPLIER_ID,

    TO_NUMBER(TO_CHAR(s.ORDER_DATE, 'YYYYMMDD')) AS ORDER_DATE_KEY,
    TO_NUMBER(TO_CHAR(s.SHIP_DATE, 'YYYYMMDD')) AS SHIP_DATE_KEY,

    s.ORDER_DATE,
    s.SHIP_DATE,
    s.COMMIT_DATE,
    s.RECEIPT_DATE,

    s.ORDER_STATUS,
    s.ORDER_PRIORITY,
    s.SHIP_MODE,
    s.RETURN_FLAG,
    s.LINE_STATUS,

    s.QUANTITY,
    s.GROSS_SALES_AMOUNT,
    s.DISCOUNT,
    s.NET_SALES_AMOUNT,
    s.TAX,
    s.SALES_AMOUNT_WITH_TAX,

    s.DAYS_TO_SHIP,
    s.SHIPPING_DURATION_DAYS,

    CURRENT_TIMESTAMP() AS MART_LOAD_TS

FROM TRAINING_DB.INTERMEDIATE.INT_SALES s;