SET LOAD_ID = TRAINING_DB.STAGING.SEQ_STG_LOAG_KEY.NEXTVAL;

CREATE OR REPLACE TABLE TRAINING_DB.STAGING.STG_ORDERS AS
SELECT
    TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS SOURCE_UPDATE_TS,

    O_ORDERKEY      AS ORDER_ID,
    O_CUSTKEY       AS CUSTOMER_ID,
    O_ORDERSTATUS   AS ORDER_STATUS,
    O_TOTALPRICE    AS TOTAL_PRICE,
    O_ORDERDATE     AS ORDER_DATE,
    O_ORDERPRIORITY AS ORDER_PRIORITY,
    O_CLERK         AS CLERK,
    O_SHIPPRIORITY  AS SHIP_PRIORITY,
    O_COMMENT       AS COMMENT,

    $LOAD_ID       AS LOAD_ID,
    CURRENT_TIMESTAMP()                            AS STG_LOAD_TS

FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;