SET LOAD_ID = TRAINING_DB.STAGING.SEQ_STG_LOAG_KEY.NEXTVAL;

CREATE OR REPLACE TABLE TRAINING_DB.STAGING.STG_PART AS
SELECT
    TO_TIMESTAMP_NTZ('2026-01-01 00:00:00') AS SOURCE_UPDATE_TS,

    P_PARTKEY     AS PART_ID,
    P_NAME        AS PART_NAME,
    P_MFGR        AS MANUFACTURER,
    P_BRAND       AS BRAND,
    P_TYPE        AS PART_TYPE,
    P_SIZE        AS PART_SIZE,
    P_CONTAINER   AS CONTAINER,
    P_RETAILPRICE AS RETAIL_PRICE,
    P_COMMENT     AS COMMENT,

    $LOAD_ID       AS LOAD_ID,
    CURRENT_TIMESTAMP()                            AS STG_LOAD_TS
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;